import { useEffect, useState } from 'react';
import type { BriefBody, BriefInput, BriefDraft, ReviewChecks } from '@platform/shared';
import { getJson, getMe, sendJson, type SuggestionRow } from './api.js';
import type { ResearchRow, Topic } from './AudienceResearch.js';
interface Record {id:string;version:number;body:BriefBody;updatedBy:string;updatedAt:string}
const empty:BriefInput={topic:'',intendedViewer:'',learnerLevel:'',learningOutcome:'',platform:'',targetDurationSeconds:60,primarySuccessMeasure:'',nextAction:'',languages:['French'],suggestionId:null,researchIds:[],exampleIds:[],factualSources:[]};
function passed(c:ReviewChecks|null){return !!c&&c.bannedTopics&&c.brandVoice&&c.frenchAccuracy&&c.learnerLevel&&c.languageFit&&c.noMisleadingPromises&&c.completeLesson&&c.learnerPractice;}
export function BriefLab({suggestions}:{suggestions:SuggestionRow[]}){
 const [records,setRecords]=useState<Record[]>([]),[record,setRecord]=useState<Record|null>(null),[input,setInput]=useState<BriefInput>(empty),[draft,setDraft]=useState<BriefDraft|null>(null),[id,setId]=useState<string>(()=>crypto.randomUUID()),[reason,setReason]=useState('Initial brief'),[confirmation,setConfirmation]=useState(''),[reviewed,setReviewed]=useState(false),[owner,setOwner]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[topics,setTopics]=useState<Topic[]>([]),[research,setResearch]=useState<ResearchRow[]>([]),[examples,setExamples]=useState<Array<{id:string;title:string|null;platform:string}>>([]),[history,setHistory]=useState<Record[]>([]),[jobs,setJobs]=useState<Array<{id:string;status:string;stage:string}>>([]);
 const body=record?.body;
 function load(){getJson<Record[]>('/api/studio/briefs').then(setRecords).catch(e=>setMessage(e.message));}
 useEffect(()=>{load();getMe().then(m=>setOwner(m.role==='owner'));getJson<{records:ResearchRow[];topics:Topic[]}>('/api/studio/research').then(p=>{setTopics(p.topics);setResearch(p.records);}).catch(()=>{});getJson<{videos:Array<{id:string;title:string|null;platform:string}>}>('/api/analysis').then(p=>setExamples(p.videos)).catch(()=>{});},[]);
 async function select(r:Record){setId(r.id);setRecord(r);setInput(r.body.input);setDraft(r.body.draft);setReviewed(false);setConfirmation('');const details=await getJson<{history:Record[];jobs:typeof jobs}>(`/api/studio/briefs/${r.id}`);setHistory(details.history);setJobs(details.jobs);setReason('Human revision');}
 function fresh(){setId(crypto.randomUUID());setRecord(null);setInput(empty);setDraft(null);setHistory([]);setJobs([]);setReason('Initial brief');setReviewed(false);setConfirmation('');}
 async function action(path:string,payload:object,method:'PUT'|'POST'='POST'){
  setBusy(true);setMessage('');try{const r=await sendJson<Record>(method,path,payload);await select(r);load();setMessage('Saved. Human review remains required.');}catch(e){setMessage(String(e));}finally{setBusy(false);}
 }
 const envelope=()=>({expectedVersion:record?.version??0,requestId:crypto.randomUUID()});
 const dirty=!!record&&(JSON.stringify(input)!==JSON.stringify(body!.input)||JSON.stringify(draft)!==JSON.stringify(body!.draft));
 const generate=(stage:'hooks'|'draft'|'checks')=>action(`/api/studio/briefs/${id}/generate`,{...envelope(),stage});
 return <details className="card studio"><summary>Hook, script & teaching brief lab</summary>
 <p className="dim">Select a topic and one intended viewer. Generated drafts require checks and explicit human approval. Nothing publishes.</p>
 <div className="studio-fields"><label>Open brief<select value={record?.id??''} onChange={e=>{const r=records.find(r=>r.id===e.target.value);if(r)void select(r).catch(e=>setMessage(String(e)));}}><option value="">Choose…</option>{records.map(r=><option key={r.id} value={r.id}>{r.body.input.topic} · v{r.version}{r.body.approval?' · approved':''}</option>)}</select></label><button onClick={fresh}>New brief</button>
 <label>Start from suggestion<select value={input.suggestionId??''} onChange={e=>{const s=suggestions.find(s=>s.id===e.target.value);setInput({...input,suggestionId:s?.id??null,topic:s?.payload.theme??input.topic,exampleIds:s?.payload.evidenceContentIds??[]});}}><option value="">Creative exploration</option>{suggestions.filter(s=>['surfaced','posted'].includes(s.status)).map(s=><option key={s.id} value={s.id}>{s.payload.theme}</option>)}</select></label>
 <label>Use audience topic<select value="" onChange={e=>{const t=topics.find(t=>t.theme===e.target.value);if(t)setInput({...input,topic:t.theme,researchIds:t.evidenceIds});}}><option value="">Choose evidence…</option>{topics.map(t=><option key={t.theme}>{t.theme}</option>)}</select></label></div>
 <div className="studio-fields">{(['topic','intendedViewer','learnerLevel','learningOutcome','platform','primarySuccessMeasure','nextAction'] as const).map(k=><label key={k}>{({topic:'Topic',intendedViewer:'One intended viewer',learnerLevel:'Learner level',learningOutcome:'One learning outcome',platform:'Platform',primarySuccessMeasure:'Primary success measure',nextAction:'One next action'})[k]}<input value={input[k]} onChange={e=>setInput({...input,[k]:e.target.value})}/></label>)}
 <label>Target duration (seconds)<input type="number" min="1" value={input.targetDurationSeconds} onChange={e=>setInput({...input,targetDurationSeconds:Number(e.target.value)})}/></label></div>
 <div>{(['Punjabi','English','French'] as const).map(l=><label key={l}><input type="checkbox" checked={input.languages.includes(l)} onChange={e=>setInput({...input,languages:e.target.checked?[...input.languages,l]:input.languages.filter(x=>x!==l)})}/>{l}</label>)}</div>
 <details><summary>Evidence and dated factual sources</summary><label>Own-channel examples / non-examples<select multiple value={input.exampleIds} onChange={e=>setInput({...input,exampleIds:Array.from(e.target.selectedOptions).map(o=>o.value)})}>{examples.map(v=><option value={v.id} key={v.id}>[{v.platform}] {v.title??v.id}</option>)}</select></label>
 {input.researchIds.map(rid=><p key={rid}>{research.find(r=>r.id===rid)?.body.text??rid}</p>)}
 {input.factualSources.map(s=><fieldset key={s.id}>{(['title','text','url','date'] as const).map(k=><label key={k}>Source {k}<input type={k==='date'?'date':'text'} value={s[k]??''} onChange={e=>setInput({...input,factualSources:input.factualSources.map(x=>x.id===s.id?{...x,[k]:k==='url'?(e.target.value||null):e.target.value}:x)})}/></label>)}<button onClick={()=>setInput({...input,factualSources:input.factualSources.filter(x=>x.id!==s.id)})}>Remove source</button></fieldset>)}<button onClick={()=>setInput({...input,factualSources:[...input.factualSources,{id:crypto.randomUUID(),title:'',text:'',url:null,date:''}]})}>Add dated factual source</button></details>
 <label>Revision / hook selection reason<input value={reason} onChange={e=>setReason(e.target.value)}/></label>
 <button disabled={busy} onClick={()=>void action(`/api/studio/briefs/${id}`,{...envelope(),body:{input,draft,revisionReason:reason}},'PUT')}>Save revision (resets review)</button>
 {record&&<><p>Revision {record.version} · {body?.approval?`Approved by ${body.approval.by}`:'Awaiting human approval'}</p><button disabled={busy||dirty} onClick={()=>void generate('hooks')}>Generate three hook approaches</button>
 {body?.hookChecks&&!passed(body.hookChecks)&&<p role="alert">Hook checks need revision: {body.hookChecks.reasons.join('; ')}. Rejected output retained in history.</p>}
 {passed(body?.hookChecks??null)&&body?.hooks.map(h=><div className="card" key={h.id}><strong>{h.approach}</strong><p>{h.text}</p><p>{h.audienceFit}</p><small>Examples: {h.evidenceContentIds.join(', ')||'none — creative exploration'}</small><button disabled={busy||dirty} onClick={()=>void action(`/api/studio/briefs/${id}/select-hook`,{...envelope(),hookId:h.id,reason})}>{body.selectedHookId===h.id?'Selected':'Choose this hook'}</button></div>)}
 <button disabled={busy||dirty||!body?.selectedHookId} onClick={()=>void generate('draft')}>Draft selected hook</button>
 {draft&&<><h3>Draft for review</h3><p className="dim">{passed(body?.draftChecks??null)?'Automated checks passed; human review still required.':'Unchecked or failed checks. Edit and run checks before approval.'}</p>
 {(['spokenScript','firstFrameText','subtitles','payoff','learnerPractice','cta'] as const).map(k=><label key={k}>{k}<textarea value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}
 {draft.visualBeats.map((b,i)=><fieldset key={i}><label>At seconds<input type="number" min="0" value={b.atSeconds} onChange={e=>setDraft({...draft,visualBeats:draft.visualBeats.map((x,n)=>n===i?{...x,atSeconds:Number(e.target.value)}:x)})}/></label>{(['visual','bRoll'] as const).map(k=><label key={k}>{k}<textarea value={b[k]} onChange={e=>setDraft({...draft,visualBeats:draft.visualBeats.map((x,n)=>n===i?{...x,[k]:e.target.value}:x)})}/></label>)}</fieldset>)}
 <button disabled={busy||dirty} onClick={()=>void generate('checks')}>Run checks on saved draft</button><p>{body?.draftChecks?.reasons.join('; ')}</p><p>Factual risks: {body?.draftChecks?.factualRisks.join('; ')||'Review all claims even if no automated flags.'}</p>
 {owner&&<><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I reviewed French accuracy, learner level, the complete lesson/practice, and factual claims</label><label>Dated sources checked / human factual confirmation<textarea value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button disabled={busy||dirty||!reviewed||!passed(body?.draftChecks??null)} onClick={()=>void action(`/api/studio/briefs/${id}/approve`,{...envelope(),factualConfirmation:confirmation,reviewedFrench:true,reviewedLevel:true,reviewedTeaching:true,reviewedFacts:true})}>Approve this exact brief revision</button></>}
 </>}
 <details><summary>History & generation jobs</summary>{history.map(r=><p key={r.version}>v{r.version} · {r.updatedBy} · {r.body.revisionReason} · {r.body.decisions.map(d=>`${d.decision}: ${d.reason}`).join('; ')}</p>)}{jobs.map(j=><p key={j.id}>{j.stage} · {j.status}{owner&&j.status==='running'&&<button onClick={async()=>{await sendJson('POST',`/api/studio/briefs/${id}/cancel-job`,{jobId:j.id});await select(record);}}>Cancel stale job</button>}</p>)}</details></>}
 <p role="status">{message}</p></details>;
}
