import type { BrainView } from '@platform/shared';
export interface AreaGuide {
  title: string; purpose: string; inputs: string; outputs: string; source: string;
  ai: string; limits: string; approval: string; good: string; failures: string; next: string;
}
export const GUIDES: Record<BrainView, AreaGuide> = {
  brain: {
    title:'Marketing Brain',purpose:'See the learning loop, current work and next useful decision in one place.',
    inputs:'Saved research, suggestions, briefs, production records, platform snapshots and insight reports.',
    outputs:'Actionable review queues, workflow connections, recorded outcomes and evidence gaps.',
    source:'Existing marketing records. The map connections describe workflow, not live traffic.',
    ai:'The existing analysts propose ideas and explain calculated patterns. This home only reads their saved work.',
    limits:'No hidden autonomous staff, live sync guarantee, invented causes or automatic publishing.',
    approval:'Jas approves teaching briefs, exact exports and confirmed publication links.',
    good:'Each attention item opens the record that needs a decision.',
    failures:'Unavailable sources are labelled. Old snapshots and small cohorts do not become confident diagnoses.',
    next:'Start with Needs attention, or follow Audience → Create → Results → Learnings.',
  },
  audience: {
    title:'Audience research',purpose:'Choose useful lessons from real questions and approved anonymous themes.',
    inputs:'Human-entered learner questions, redacted objections, public comments and references.',
    outputs:'Distinct inbox evidence and topic opportunities with reasons.',
    source:'Approved entries, source dates and optional public links; lists contain the latest 500 entries.',
    ai:'The current topic grouping is deterministic. Brief drafting can use selected evidence.',
    limits:'No private-message ingestion, sensitive-trait inference, demand estimates or invented personas.',
    approval:'A human must redact and approve every entry.',
    good:'A specific question, dated source, clear relevance and a concrete teaching outcome.',
    failures:'Duplicates, spam, reactions and reference videos must not inflate question counts. An old source may need review.',
    next:'Use a topic in Briefs and select the exact supporting entries.',
  },
  suggestions: {
    title:'Suggestions',purpose:'Review proposed video ideas before committing production time.',
    inputs:'Brand rules, content notes, snapshots, stored insight reports and creative observations.',
    outputs:'Checked ideas with hooks, format, rationale and saved evidence references.',
    source:'The existing suggestion analyst and its recorded prompt evidence.',
    ai:'Drafts ideas and runs the mandatory banned-topic and brand-voice checks.',
    limits:'A proposed hook is not a verified explanation or a promised result.',
    approval:'A human chooses an idea. Posted/Skipped is feedback; it does not publish or confirm X14 lineage.',
    good:'One useful promise, a suitable learner and evidence you can inspect.',
    failures:'Creative exploration has weak evidence. Historical suggestions may have no saved source snapshot.',
    next:'Open the idea in Briefs, select a hook, review the script and approve the exact revision.',
  },
  'idea-map': {
    title:'Ideas & hypotheses',purpose:'See which proposed ideas have evidence and where they are in the workflow.',
    inputs:'Suggestions, their cited sources, brief references, production records and X6 inferred outcomes.',
    outputs:'Readable idea → evidence → brief → outcome relationships.',
    source:'Saved suggestion evidence and explicit studio references. Automatic X6 matches stay inferred.',
    ai:'May suggest a hypothesis; a shared tag does not prove that a video came from that idea.',
    limits:'There is no preregistered experiment register yet. Published does not mean supported.',
    approval:'Tags need human approval; confirmed published-video lineage is owner-only.',
    good:'A proposed idea has an explicit brief and a confirmed video link before its outcome is treated as that idea’s result.',
    failures:'A format match may connect unrelated videos. Missing links stay unknown.',
    next:'Review the linked video in Results, then plan a single-change follow-up.',
  },
  briefs: {
    title:'Brief lab',purpose:'Turn a chosen topic into a filmable, reviewable teaching brief.',
    inputs:'Viewer, learner level, topic, learning outcome, platform, duration, success measure, research and dated sources.',
    outputs:'Three checked hook approaches, a selected hook, script, visual beats, subtitles, practice and CTA.',
    source:'Human input, approved evidence and the existing drafting model. Every save creates a revision.',
    ai:'Generates only when requested, under the monthly cap, then runs the required checks.',
    limits:'Checks cannot guarantee French accuracy or current factual claims. No filming, media processing or publishing.',
    approval:'Only the owner approves the exact revision after teaching and factual review.',
    good:'One viewer, one learning outcome, a complete lesson and a meaningful next step.',
    failures:'Edits reset checks/approval; a stale revision or failed check must be resolved before handoff.',
    next:'Create a production item and lock the approved brief revision.',
  },
  production: {
    title:'Production & review',purpose:'Keep filming, edit feedback and exact export approvals attached to one concept.',
    inputs:'A versioned brief, owner, dates, blockers, approved asset references and timecoded requests.',
    outputs:'Selected → ready to film → filmed → edit review → export approved → posted → reviewed.',
    source:'Human-maintained production records, immutable asset identities and review history.',
    ai:'Does not edit, watch, upload or publish the video. The board shows saved states.',
    limits:'Contributor names are responsibility labels, not access roles. An asset fingerprint is supplied by a human.',
    approval:'Owner review is required for the exact export and its link to an already ingested published video.',
    good:'All blockers and requests resolved, complete checks, and approval naming the right export.',
    failures:'Changing an export resets its review. Posted items and historical lineage cannot be casually rewritten.',
    next:'After external publication and ingestion, confirm the link here and inspect Results.',
  },
  performance: {
    title:'Results & diagnosis',purpose:'See what was recorded and which explanation is worth testing.',
    inputs:'Platform snapshots, human content notes, comparable history and stored patterns.',
    outputs:'Observed records, a labelled comparison, hypotheses, unknowns and a proposed next test.',
    source:'Canonical content UUIDs. Engagement reuses X2 rates; native provenance is shown when present.',
    ai:'This diagnosis is deterministic. AI-generated historical interpretations are shown separately as stored patterns.',
    limits:'No causal verdict, reconstructed retention curve, missing metric converted to zero, or video-level sales attribution.',
    approval:'A human decides what to test and approves any resulting brief.',
    good:'At least eight other comparable scored videos at the same day, platform, format and exposure, with limitations visible.',
    failures:'Small cohorts, missing exact-age snapshots, unknown ad exposure and incompatible native definitions.',
    next:'Open the content journey, inspect its notes, then draft one controlled creative change.',
  },
  analysis: {
    title:'Content notes',purpose:'Tell the system what a video contains; this is the existing Analysis editor.',
    inputs:'Human description, hook, format, CTA, ad status, idea origin and cross-platform twins.',
    outputs:'Saved context used by metrics, insight grouping and suggestions.',
    source:'Human review of your own videos. Creative memory holds versioned descriptive and timestamped notes.',
    ai:'Uses these inputs later; it does not automatically watch this video.',
    limits:'A description or tag is not a measured cause. Ad status is allowed to remain unknown.',
    approval:'Owner or marketing can save context. Asset observations must be reviewed by a human.',
    good:'Accurate format and opening, honest ad status, and the correct twins.',
    failures:'Wrong platform IDs, unreviewed timestamps and stale export notes can weaken later analysis.',
    next:'Open Results for the video and use reviewed examples in a new brief.',
  },
  metrics: {
    title:'Metrics & twins',purpose:'Inspect exact calculations and snapshot history behind the result.',
    inputs:'Daily snapshots, manual ad runs, follower observations and X1 paired videos.',
    outputs:'X2 rates, day 1/7/30 view observations, follower normalization and ad-window time splits.',
    source:'Existing shared pure metric functions. Approximate observations carry the actual day.',
    ai:'Does not compute these numbers; deterministic code does.',
    limits:'The ad-window split is a time split, not paid versus organic. Twins are observational comparisons.',
    approval:'People maintain pairing and ad dates in Content notes.',
    good:'Read the snapshot date, units, denominator and missing-data label before comparing.',
    failures:'Thin history, unreported shares and different platform metric definitions.',
    next:'Return to diagnosis, or add the missing notes and wait for a comparable window.',
  },
  learnings: {
    title:'Creative memory & learnings',purpose:'Keep our own recorded evidence visible when choosing the next video.',
    inputs:'Stored platform-specific X6 patterns and immutable revisions of manual creative observations.',
    outputs:'Evidence cards with dates, contributing videos, limitations and links back to the work.',
    source:'Saved insight reports and reviewed human notes; no generic playbook is manufactured.',
    ai:'Explains historical patterns and can retrieve these sources while drafting future ideas.',
    limits:'A reporting floor is not proof. Contradicting experiments and human-promoted/retired learning rules need the future experiment register.',
    approval:'Human review of notes and a new brief remain mandatory.',
    good:'A learning names its platform, source report, sample and evidence, and survives another test.',
    failures:'Stale reports, unreviewed notes, confounded comparisons and generalizing one successful video.',
    next:'Open a source video, inspect counterevidence where recorded, and plan a repeat or a single-change test.',
  },
  insights: {
    title:'Pattern reports',purpose:'Run and inspect the existing X6 analysis, including proposed hypothesis tags.',
    inputs:'Content analysis, engagement-only scores and paired videos.',
    outputs:'Per-platform group medians, sample sizes, cautions, optional narrative and tag proposals.',
    source:'The last stored report, generated nightly or by an explicit manual request.',
    ai:'Words the supplied deterministic figures. A missing key or budget can produce numbers-only output.',
    limits:'Eight is a reporting threshold, not statistical significance. Pairing does not control audience, timing or distribution.',
    approval:'Every proposed tag needs an explicit Approve or Reject decision.',
    good:'You can open the evidence behind each pattern and explain its limitations.',
    failures:'Sparse groups abstain; a stale report does not describe changes after its date.',
    next:'Use Learnings to connect the report to source videos and future briefs.',
  },
  kpis: {
    title:'Business visibility',purpose:'Follow the enrollments we can see and weekly analysis coverage.',
    inputs:'Stripe records and aggregate counts handed over by the portal.',
    outputs:'Monthly business visibility and coverage against the existing weekly goal.',
    source:'Owner-only endpoints. The two databases remain separate.',
    ai:'Does not attribute enrollments or revenue to a video.',
    limits:'Historical Stripe-visible figures are permanently incomplete; renewals may be estimated.',
    approval:'Owner access is required. Marketing cannot retrieve these figures.',
    good:'Read completeness and exact/estimated labels alongside each figure.',
    failures:'Missing portal configuration and historical payment channels outside Stripe.',
    next:'Resolve current data gaps without inventing historical enrollments.',
  },
  'run-log': {
    title:'System activity',purpose:'Inspect the real technical audit trail when work fails or is rejected.',
    inputs:'Existing agent_logs records.',
    outputs:'Agent, tool, result, timestamp, duration and recorded errors.',
    source:'The latest 100 owner-only log rows. This is not a live monitoring feed.',
    ai:'Every orchestrator call is logged; unauthorized tools are rejected by the router.',
    limits:'A completed run is not proof that marketing improved. No extra agents are implied.',
    approval:'Owner access is required; the shared Brain only shows marketing record activity.',
    good:'A failed operation is traceable to a recorded run without exposing secrets.',
    failures:'A missing event means unknown; it must never become a fake “all systems healthy” indicator.',
    next:'Use the relevant workflow to correct input, or investigate the recorded system error.',
  },
};
