import { useEffect, useState } from 'react';
import type { ProductionBody, ProductionEdit, BriefBody, StudioRecord } from '@platform/shared';
import { getJson, getMe, sendJson } from './api.js';
const labels={speech:'Speech is intelligible',musicMasking:'Music does not mask speech',frenchSubtitles:'French and subtitles are accurate',safeText:'Text stays inside platform safe areas',readability:'Examples are readable',hookPayoff:'Hook delivers its payoff',repetition:'Unnecessary repetition removed',rightsConsent:'Rights and consent verified',factualAccuracy:'Factual claims checked against dated sources',cta:'One clear CTA'};
const blank=():ProductionEdit=>({briefId:'',briefVersion:1,owner:'',dueDate:null,responsibilities:{preparer:'Eknoor',recorder:'Jas',editor:'Loop Studio',reviewer:'Jas'},blockers:[],assets:[],currentAssetVersion:null,requests:[],checklist:(Object.keys(labels) as Array<keyof typeof labels>).map(key=>({key,status:'pending',note:''}))});
export function ProductionBoard(){
 const [items,setItems]=useState<StudioRecord[]>([]),[briefs,setBriefs]=useState<StudioRecord[]>([]),[record,setRecord]=useState<StudioRecord|null>(null),[form,setForm]=useState<ProductionEdit>(blank),[id,setId]=useState<string>(()=>crypto.randomUUID()),[history,setHistory]=useState<StudioRecord[]>([]),[brief,setBrief]=useState<BriefBody|null>(null),[links,setLinks]=useState<Array<Record<string,unknown>>>([]),[videos,setVideos]=useState<Array<{id:string;platform:string;title:string|null}>>([]),[owner,setOwner]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[exact,setExact]=useState(false),[contentId,setContentId]=useState('');
 const [asset,setAsset]=useState({version:'',url:'',fingerprint:'',durationSeconds:60,approvedReference:true as const});
 const body=record?.body as ProductionBody|undefined;
 function editable(b:ProductionBody):ProductionEdit{const {stage:_,approval:__,...rest}=b;return rest;}
 const dirty=!!body&&JSON.stringify(form)!==JSON.stringify(editable(body));
 const locked=body?.stage==='posted'||body?.stage==='reviewed';
 async function refresh(){try{setItems(await getJson<StudioRecord[]>('/api/studio/production'));setBriefs(await getJson<StudioRecord[]>('/api/studio/briefs'));}catch(e){setMessage(String(e));}}
 useEffect(()=>{void refresh();getMe().then(m=>setOwner(m.role==='owner'));getJson<{videos:typeof videos}>('/api/analysis').then(p=>setVideos(p.videos)).catch(e=>setMessage(String(e)));},[]);
 async function select(r:StudioRecord){const d=await getJson<{record:StudioRecord;history:StudioRecord[];brief:StudioRecord;lineage:typeof links}>(`/api/studio/production/${r.id}`);setRecord(d.record);setId(r.id);setForm(editable(d.record.body as ProductionBody));setBrief(d.brief.body as BriefBody);setHistory(d.history);setLinks(d.lineage);setExact(false);setContentId('');}
 function fresh(){setRecord(null);setId(crypto.randomUUID());setForm(blank());setHistory([]);setBrief(null);setLinks([]);setExact(false);}
 const envelope=()=>({expectedVersion:record?.version??0,requestId:crypto.randomUUID()});
 async function action(suffix:string,payload:object,method:'POST'|'PUT'='POST'){setBusy(true);setMessage('');try{const r=await sendJson<StudioRecord>(method,`/api/studio/production/${id}${suffix}`,payload);await select(r);await refresh();setMessage('Saved. This action does not publish.');}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 const next=body?({selected:'brief_approved',brief_approved:'filmed',filmed:'edit_review',edit_review:'approved',posted:'reviewed'} as Partial<Record<ProductionBody['stage'],ProductionBody['stage']>>)[body.stage]:null;
 const current=form.assets.find(a=>a.version===form.currentAssetVersion);
 return <details className="card studio" onToggle={e=>{if(e.currentTarget.open)void refresh();}}><summary>Production & edit review</summary>
 <p className="dim">Manual handoff from an approved brief. Existing Suggestions Posted/Skipped controls remain separate. Collaborator names are labels and grant no access. Latest 500 items.</p>
 <div className="studio-fields"><label>Open production item<select value={record?.id??''} onChange={e=>{const r=items.find(x=>x.id===e.target.value);if(r)void select(r).catch(e=>setMessage(String(e)));}}><option value="">Choose…</option>{items.map(r=><option key={r.id} value={r.id}>{String(r.body['owner'])} · {String(r.body['stage'])} · {r.id.slice(0,8)}</option>)}</select></label><button onClick={fresh}>New production item</button></div>
 <fieldset disabled={busy||locked}><legend>Versioned handoff</legend>
 <label>Approved brief revision<select disabled={!!record} value={form.briefId} onChange={e=>{const r=briefs.find(r=>r.id===e.target.value);if(r){setForm({...form,briefId:r.id,briefVersion:r.version});setBrief(r.body as BriefBody);}}}><option value="">Choose an approved brief…</option>{briefs.filter(r=>(r.body as BriefBody).approval?.version===r.version||r.id===form.briefId).map(r=><option key={r.id} value={r.id}>{(r.body as BriefBody).input.topic} · v{r.id===form.briefId?form.briefVersion:r.version}</option>)}</select></label>
 <div className="studio-fields"><label>Responsible owner<input value={form.owner} onChange={e=>setForm({...form,owner:e.target.value})}/></label><label>Due date<input type="date" value={form.dueDate??''} onChange={e=>setForm({...form,dueDate:e.target.value||null})}/></label>{(['preparer','recorder','editor','reviewer'] as const).map(k=><label key={k}>{k} (label)<input value={form.responsibilities[k]} onChange={e=>setForm({...form,responsibilities:{...form.responsibilities,[k]:e.target.value}})}/></label>)}</div>
 <label>Blockers (one per line)<textarea value={form.blockers.join('\n')} onChange={e=>setForm({...form,blockers:e.target.value.split('\n').filter(Boolean)})}/></label>
 <h3>Approved asset references</h3><p>Use an immutable version link and a human-verified checksum or version identity. No file is fetched or uploaded here. Existing version identities cannot be overwritten.</p>
 {form.assets.map(a=><p key={a.version}><label><input type="radio" name="production-asset" checked={form.currentAssetVersion===a.version} onChange={()=>setForm({...form,currentAssetVersion:a.version,checklist:blank().checklist})}/>{a.version}</label> · <a href={a.url} target="_blank" rel="noreferrer">Open asset</a> · {a.durationSeconds}s · {a.fingerprint}</p>)}
 <div className="studio-fields">{(['version','url','fingerprint'] as const).map(k=><label key={k}>New asset {k}<input value={asset[k]} onChange={e=>setAsset({...asset,[k]:e.target.value})}/></label>)}<label>Duration (seconds)<input type="number" min="1" value={asset.durationSeconds} onChange={e=>setAsset({...asset,durationSeconds:Number(e.target.value)})}/></label></div><button onClick={()=>{setForm({...form,assets:[...form.assets,asset],currentAssetVersion:asset.version,checklist:blank().checklist});setAsset({...asset,version:'',url:'',fingerprint:''});}}>Add approved reference as new version</button>
 <h3>Finite revision list</h3>{form.requests.map(r=><fieldset key={r.id}><legend>{r.assetVersion}</legend><label>Type<select value={r.type} onChange={e=>setForm({...form,requests:form.requests.map(x=>x.id===r.id?{...x,type:e.target.value as typeof r.type}:x)})}><option value="defect">Measurable defect</option><option value="editorial_suggestion">Editorial suggestion</option></select></label><label>Timecode (seconds, optional)<input type="number" min="0" value={r.atSeconds??''} onChange={e=>setForm({...form,requests:form.requests.map(x=>x.id===r.id?{...x,atSeconds:e.target.value===''?null:Number(e.target.value)}:x)})}/></label><label>Requested change<textarea value={r.text} onChange={e=>setForm({...form,requests:form.requests.map(x=>x.id===r.id?{...x,text:e.target.value}:x)})}/></label><label>Resolution<textarea value={r.resolution} onChange={e=>setForm({...form,requests:form.requests.map(x=>x.id===r.id?{...x,resolution:e.target.value}:x)})}/></label><label><input type="checkbox" checked={r.status==='resolved'} onChange={e=>setForm({...form,requests:form.requests.map(x=>x.id===r.id?{...x,status:e.target.checked?'resolved':'open'}:x)})}/>Resolved or explicitly declined with reason</label>{r.atSeconds!==null&&<a href={`${form.assets.find(a=>a.version===r.assetVersion)?.url.split('#')[0]}#t=${r.atSeconds}`} target="_blank" rel="noreferrer">Open at timecode (player support varies)</a>}</fieldset>)}
 <button disabled={!current||form.requests.length>=100} onClick={()=>setForm({...form,requests:[...form.requests,{id:crypto.randomUUID(),assetVersion:current!.version,atSeconds:null,type:'defect',text:'',status:'open',resolution:''}]})}>Add revision request</button>
 <p className="dim">Describe observed defects or editorial preferences. Do not claim a retention drop without viewer data.</p>
 <h3>Review checklist — {form.currentAssetVersion??'select an asset'}</h3>{form.checklist.map(c=><div className="studio-fields" key={c.key}><label>{labels[c.key]}<select value={c.status} onChange={e=>setForm({...form,checklist:form.checklist.map(x=>x.key===c.key?{...x,status:e.target.value as typeof c.status}:x)})}><option value="pending">Not yet reviewed</option><option value="pass">Checked and passed</option>{!['rightsConsent','factualAccuracy'].includes(c.key)&&<option value="not_applicable">Not applicable — explanation required</option>}</select></label><label>Evidence / review note<input value={c.note} onChange={e=>setForm({...form,checklist:form.checklist.map(x=>x.key===c.key?{...x,note:e.target.value}:x)})}/></label></div>)}
 <button onClick={()=>void action('',{...envelope(),body:form},'PUT')}>Save revision (invalidates export approval)</button></fieldset>
 {brief&&<details><summary>Exact teaching brief v{form.briefVersion}: {brief.input.topic}</summary><p>{brief.input.intendedViewer} · {brief.input.learningOutcome} · {brief.input.platform} · {brief.input.targetDurationSeconds}s</p><p>Success measure: {brief.input.primarySuccessMeasure} · Next action: {brief.input.nextAction}</p><p style={{whiteSpace:'pre-wrap'}}>{brief.draft?.spokenScript}</p><p>First frame: {brief.draft?.firstFrameText}</p>{brief.draft?.visualBeats.map((b,i)=><p key={i}>{b.atSeconds}s · {b.visual} · B-roll: {b.bRoll}</p>)}<p>Subtitles: {brief.draft?.subtitles}</p><p>Payoff: {brief.draft?.payoff} · Practice: {brief.draft?.learnerPractice} · CTA: {brief.draft?.cta}</p><p>Factual confirmation: {brief.approval?.factualConfirmation}</p></details>}
 {body&&<><p>Stage: <strong>{body.stage.replaceAll('_',' ')}</strong> · revision {record!.version}</p>{body.approval&&<p>Export {body.approval.assetVersion} ({body.approval.fingerprint}) approved by {body.approval.by} at {body.approval.at}, brief v{body.approval.briefVersion}.</p>}
 {next&&<>{next==='approved'&&<label><input type="checkbox" checked={exact} onChange={e=>setExact(e.target.checked)}/>I reviewed this exact export, all checklist items and resolved revision requests</label>}<button disabled={busy||dirty||next==='approved'&&(!owner||!exact)} onClick={()=>void action('/advance',{...envelope(),stage:next,reviewedExactVersion:exact})}>Record {next.replaceAll('_',' ')}</button></>}
 {owner&&['approved','posted'].includes(body.stage)&&<fieldset><legend>Confirm an already published video</legend><p>This records lineage only. Choose the ingested content corresponding to this exact approved export.</p><select value={contentId} onChange={e=>setContentId(e.target.value)}><option value="">Choose existing content…</option>{videos.map(v=><option key={v.id} value={v.id}>[{v.platform}] {v.title??v.id}</option>)}</select><label><input type="checkbox" checked={exact} onChange={e=>setExact(e.target.checked)}/>I confirm this video uses the exact approved export</label><button disabled={busy||dirty||!exact||!contentId} onClick={()=>void action('/confirm-posted',{...envelope(),contentId,confirmedExactExport:true})}>Record confirmed lineage / posted</button></fieldset>}
 <details><summary>Confirmed lineage & revision history</summary><p>Historical X6 matching stays inferred and separate. These links are human confirmed.</p>{links.map(l=><p key={String(l['id'])}>Content UUID {String(l['content_uuid'])} ← brief v{String(l['brief_version'])} / export {String(l['asset_version'])} · {String(l['confirmed_by'])}</p>)}{history.map(h=><p key={h.version}>v{h.version} · {h.updatedBy} · {h.updatedAt} · {String(h.body['stage'])}</p>)}</details></>}
 <p role="status">{message}</p></details>;
}
